"""Evaluate hard instance assignments over a fixed spread of calibrated views."""
import argparse,json
from pathlib import Path
import numpy as np,torch
from gsplat.rendering import rasterization
p=argparse.ArgumentParser();p.add_argument('labels',type=Path);p.add_argument('--tag',required=True);p.add_argument('--views',type=int,default=64);args=p.parse_args();r=(Path(__file__).resolve().parents[2]/'outputs/images/A_MARCEAU/gaussian_editable');stage=r/'rendered_scene/object_scene';catalog=json.loads((r/'rendered_gaussian_instances.json').read_text())['objects'];manifest=json.loads((stage/'detection_manifest.json').read_text());mapping={(o['view'],o['detection_index']):obj['id'] for obj in catalog for o in obj['observations']};classes=len(catalog)+1;labels=torch.as_tensor(np.load(args.labels),device='cuda',dtype=torch.int64);features=torch.nn.functional.one_hot(labels,classes).float();ckpt=torch.load(r.parent/'gs/ckpts/ckpt_7999_rank0.pt',map_location='cuda',weights_only=False);s=ckpt['splats'];T=np.array(ckpt['transform']);scale=np.cbrt(np.linalg.det(T[:3,:3]));cams=json.loads((r.parent/'gs_data/cameras.json').read_text());quats=torch.nn.functional.normalize(s['quats'],dim=-1);scales=s['scales'].exp();opacity=s['opacities'].sigmoid().reshape(-1);confusion=torch.zeros((classes,classes),device='cuda',dtype=torch.int64);selected=np.linspace(0,len(manifest['views'])-1,args.views).astype(int)
with torch.inference_mode():
 for j,index in enumerate(selected):
  view=manifest['views'][index];record=json.loads((stage/'detections'/f'{view}.json').read_text());data=np.load(stage/'detections'/f'{view}.npz');hh,ww=map(int,data['shape']);h,w=hh//2,ww//2;target=np.zeros((h,w),np.int64);known=np.ones((h,w),bool)
  for obs in sorted(record['instances'],key=lambda x:x['pixels'],reverse=True):
   mask=np.unpackbits(data['masks_packed'][obs['index']],count=hh*ww).reshape(hh,ww)[::2,::2][:h,:w].astype(bool);gid=mapping.get((view,obs['index']))
   if gid is None:known[mask]=False
   else:target[mask]=gid;known[mask]=True
  pose=T@np.linalg.inv(np.array(cams[view]['extrinsic']));pose[:3,:3]/=scale;K=np.array(cams[view]['intrinsic']);K[:2]*=.5;rendered,alpha,_=rasterization(s['means'],quats,scales,opacity,features,torch.tensor(np.linalg.inv(pose),dtype=torch.float32,device='cuda')[None],torch.tensor(K,dtype=torch.float32,device='cuda')[None],w,h,render_mode='RGB',radius_clip=3,channel_chunk=32);pred=rendered[0].argmax(-1);valid=torch.as_tensor(known,device='cuda')&(alpha[0,...,0]>.2);gt=torch.as_tensor(target,device='cuda');confusion+=torch.bincount(gt[valid]*classes+pred[valid],minlength=classes*classes).reshape(classes,classes)
  if (j+1)%16==0:print('SEMANTIC_EVAL_VIEWS',j+1,len(selected),flush=True)
a=confusion.cpu().numpy();intersection=np.diag(a);union=a.sum(0)+a.sum(1)-intersection;iou=intersection/np.maximum(union,1);ids=np.arange(classes);eligible=(a.sum(1)>=100)&(ids>0);rows=[dict(id=obj['id'],name=obj['name'],label=obj['label'],iou=float(iou[obj['id']]),target_pixels=int(a[obj['id']].sum()),predicted_pixels=int(a[:,obj['id']].sum())) for obj in catalog];report=dict(views=len(selected),mean_object_iou=float(iou[eligible].mean()),median_object_iou=float(np.median(iou[eligible])),pixel_accuracy=float(intersection.sum()/a.sum()),evaluated_objects=int(eligible.sum()),objects=rows,scope='Agreement with SAM3 instance graph on a fixed set of actual Gaussian renders, not human ground truth.');out=r/'semantic_refinement';out.mkdir(exist_ok=True);(out/(args.tag+'_evaluation.json')).write_text(json.dumps(report,indent=2));np.save(out/(args.tag+'_confusion.npy'),a);print('SEMANTIC_EVALUATION',args.tag,report['mean_object_iou'],report['median_object_iou'],flush=True)
